---
deployment:
  tasks:
    # ============================================
    # BACKEND DEPLOYMENT
    # ============================================
    - /bin/cp -Rf src/. /home/vayunexs/inv-api.vayunexsolution.com/src/
    - /bin/cp -Rf database/. /home/vayunexs/inv-api.vayunexsolution.com/database/
    - /bin/cp -Rf scripts/. /home/vayunexs/inv-api.vayunexsolution.com/scripts/
    - /bin/cp -f index.js /home/vayunexs/inv-api.vayunexsolution.com/
    - /bin/cp -f package.json /home/vayunexs/inv-api.vayunexsolution.com/
    - /bin/cp -f package-lock.json /home/vayunexs/inv-api.vayunexsolution.com/
    
    # ============================================
    # FRONTEND DEPLOYMENT (Build folder only)
    # ============================================
    - /bin/cp -Rf vayunex-ui/dist/. /home/vayunexs/inventory.vayunexsolution.com/
