---
deployment:
  tasks:
    # ============================================
    # DEBUG START
    # ============================================
    - touch /home/vayunexs/deploy_start_$(date +%s).txt
    
    # ============================================
    # BACKEND DEPLOYMENT
    # ============================================
    # Create directories
    - mkdir -p /home/vayunexs/inv-api.vayunexsolution.com/src
    - mkdir -p /home/vayunexs/inv-api.vayunexsolution.com/database
    - mkdir -p /home/vayunexs/inv-api.vayunexsolution.com/scripts
    
    # Copy files
    - /bin/cp -Rf src/* /home/vayunexs/inv-api.vayunexsolution.com/src/
    - /bin/cp -Rf database/* /home/vayunexs/inv-api.vayunexsolution.com/database/
    - /bin/cp -Rf scripts/* /home/vayunexs/inv-api.vayunexsolution.com/scripts/
    - /bin/cp -f index.js /home/vayunexs/inv-api.vayunexsolution.com/
    - /bin/cp -f package.json /home/vayunexs/inv-api.vayunexsolution.com/
    - /bin/cp -f package-lock.json /home/vayunexs/inv-api.vayunexsolution.com/
    
    # ============================================
    # FRONTEND DEPLOYMENT (Pre-built)
    # ============================================
    # Create directory
    - mkdir -p /home/vayunexs/inventory.vayunexsolution.com

    # Copy pre-built files from repository
    - /bin/cp -Rf vayunex-ui/dist/* /home/vayunexs/inventory.vayunexsolution.com/
    
    # ============================================
    # DEBUG END
    # ============================================
    - touch /home/vayunexs/deploy_success_$(date +%s).txt
